"""Application constants for Esnaad Code."""

# Agent Loop Limits
DEFAULT_MAX_ITERATIONS = 50
DEFAULT_SUBTASK_MAX_ITERATIONS = 20
DEFAULT_TIMEOUT_SECONDS = 1800  # 30 minutes
DEFAULT_SUBTASK_TIMEOUT = 120  # 2 minutes
DEFAULT_MAX_RETRIES = 2

# Clarification System
MAX_CLARIFICATION_QUESTIONS = 5
CLARIFICATION_AUTO_TIMEOUT = 300  # 5 minutes

# Tool Limits
MAX_FILE_SIZE_BYTES = 1_000_000  # 1MB
MAX_OUTPUT_CHARS = 50_000
COMMAND_TIMEOUT = 60
SEARCH_MAX_RESULTS = 100

# File Reading
DEFAULT_READ_LINES = 2000
MAX_LINE_LENGTH = 2000

# LLM Defaults
DEFAULT_MODEL = "gpt-4"
DEFAULT_TEMPERATURE = 0.7
DEFAULT_MAX_TOKENS = 4096
DEFAULT_LLM_TIMEOUT = 60.0

# Application
APP_NAME = "esnaad"
CONFIG_DIR_NAME = ".esnaad"
PREFERENCES_FILE = "preferences.json"
MEMORY_FILE = "memory.json"

# Rules System
RULES_FILE_NAME = "ESNAAD.md"
